static const char* MAINOOO = 
	"#include <stddef.h>\n"
	"#include <stdio.h>\n"
	"#include <stdlib.h>\n"
	"#include <stdio.h>\n"
	"#include <string.h>\n"
	"\n"
	"\n"
	"typedef unsigned int u32;\n"
	"typedef unsigned long u64;\n"
	"\n"
	"typedef char bool;\n"
	"#define false 0\n"
	"#define true 1\n"
	"\n"
	"\n"
	"\n"
	"u64 max(u64 v1 , u64 v2){\n"
	"	return v1>v2?v1:v2;\n"
	"}\n"
	"u64 min(u64 v1 , u64 v2){\n"
	"	return v1>v2?v2:v1;\n"
	"}\n"
	"void* Push(char* val , u32 sizeofstr ,u64 pos,  u64* dataSize , u64* usedData , char* data){\n"
	"	\n"
	"	if(usedData+sizeofstr>= dataSize){\n"
	"		u64 newDataSize = *usedData+sizeofstr+0x1000;//*dataSize+max(0x1000,*usedData+sizeofstr);\n"
	"		data=realloc(data,newDataSize);\n"
	"		/*char* newdata = (char*)malloc(newDataSize);\n"
	"		memcpy(newdata, data, *dataSize);\n"
	"		free(data);\n"
	"		data=newdata;*/\n"
	"		*dataSize=newDataSize; \n"
	"	}\n"
	"	if(pos>=*dataSize){\n"
	"		u64 newDataSize = pos+sizeofstr+0x1000;//*dataSize+max(0x1000,*usedData+sizeofstr);\n"
	"		data=realloc(data, newDataSize);\n"
	"		/*char* newdata = (char*)malloc(*dataSize+max);\n"
	"		memcpy(newdata, data, *dataSize);\n"
	"		free(data);\n"
	"		data=newdata;*/\n"
	"		*dataSize=newDataSize;\n"
	"	}\n"
	"	for(u32 i = *usedData+sizeofstr; i>pos+sizeofstr; i--){\n"
	"		data[i-1] = data[i-sizeofstr-1];\n"
	"	}\n"
	"	\n"
	"	for(u32 i = 0 ; i < sizeofstr ; i++){\n"
	"		data[i+pos]=val[i];\n"
	"	}\n"
	"	*usedData+=sizeofstr;\n"
	"	return data;\n"
	"}\n"
	"\n"
	"\n"
	"\n"
	"unsigned long GetFileSize(FILE* fl){\n"
	"	if(fl==NULL){\n"
	"		printf(\"err in file\n\");\n"
	"		return -1;\n"
	"	}\n"
	"	long prev=ftell(fl);\n"
	"	if(fseek(fl, 0L, SEEK_END)==-1){\n"
	"		printf(\"files to fseek\");\n"
	"		return -1;\n"
	"	}\n"
	"	unsigned long fileSize = ftell(fl);\n"
	"	fseek(fl, prev, SEEK_SET);\n"
	"	return fileSize;\n"
	"\n"
	"}\n"
	"\n"
	"\n"
	"void* readFile(const char* fileName , unsigned long * sizeOUT){\n"
	"	FILE* file = fopen(fileName, \"r\");\n"
	"	if(file==NULL){\n"
	"		printf(\"err in opening file\n\");\n"
	"		return NULL;\n"
	"	}\n"
	"	unsigned long fileSz = GetFileSize(file);\n"
	"	*sizeOUT=fileSz;\n"
	"	\n"
	"	if(fileSz!=-1){\n"
	"		char* data = (char*)malloc(fileSz);\n"
	"		fread(data, fileSz, 1, file);\n"
	"		\n"
	"		\n"
	"		fclose(file);\n"
	"		return data;\n"
	"	}\n"
	"\n"
	"	fclose(file);\n"
	"	return NULL;\n"
	"}\n"
	"\n"
	"\n"
	"\n"
	"void WriteConstCharHaderFile(const char* haderName, char* matrixName , char* data , u64 sizeofData ,bool append ){\n"
	"	FILE* hader = fopen(haderName, append?\"a\":\"w\");\n"
	"	if(!hader){\n"
	"		printf(\"Erorr in writing hader file\");\n"
	"		return;\n"
	"	}\n"
	"	for(u32 i = 0 ; i < strlen(matrixName); i++){\n"
	"		switch (matrixName[i]) {\n"
	"			case '.':\n"
	"				matrixName[i]='_';\n"
	"				break;\n"
	"			case '\"':\n"
	"				matrixName[i]='_';\n"
	"				break;\n"
	"			case  '\'':\n"
	"				matrixName[i]='_';\n"
	"				break;\n"
	"			case '@':\n"
	"				matrixName[i]='/';\n"
	"				break;\n"
	"			case '%':\n"
	"				matrixName[i]='_';\n"
	"				break;\n"
	"			default:\n"
	"				break;\n"
	"		};\n"
	"		\n"
	"	}\n"
	"	if( matrixName[0] <='9' && matrixName[0] >='0'){\n"
	"		matrixName[0]='_';\n"
	"	}\n"
	"	\n"
	"	\n"
	"	if(append){\n"
	"		fprintf(hader, \"\n\n\n/********************************************%s***********************************************/\n\",matrixName);\n"
	"	}\n"
	"	fprintf(hader, \"static const char* %s = \n\",matrixName);\n"
	"	fwrite(data, 1, sizeofData-1,hader);\n"
	"	//fwrite(const void *__restrict ptr, size_t size, size_t n, FILE *__restrict s)\n"
	"	fprintf(hader, \";\");\n"
	"	fclose(hader);\n"
	"	return;\n"
	"}\n"
	"\n"
	"\n"
	"\n"
	"void WriteMatrixHaderFile(const char* haderName, char* matrixName , char* data , u64 sizeofData,bool append){\n"
	"	FILE* hader = fopen(haderName, append?\"a\":\"w\");\n"
	"	if(!hader){\n"
	"		printf(\"Erorr in writing hader file\");\n"
	"		return;\n"
	"	}\n"
	"	for(u32 i = 0 ; i < strlen(matrixName); i++){\n"
	"		switch (matrixName[i]) {\n"
	"			case '.':\n"
	"				matrixName[i]='_';\n"
	"				break;\n"
	"			case '\"':\n"
	"				matrixName[i]='_';\n"
	"				break;\n"
	"			case  '\'':\n"
	"				matrixName[i]='_';\n"
	"				break;\n"
	"			case '@':\n"
	"				matrixName[i]='/';\n"
	"				break;\n"
	"			case '%':\n"
	"				matrixName[i]='_';\n"
	"				break;\n"
	"			default:\n"
	"				break;\n"
	"		};\n"
	"		\n"
	"	}\n"
	"	if( matrixName[0] <='9' && matrixName[0] >='0'){\n"
	"		matrixName[0]='_';\n"
	"	}\n"
	"	\n"
	"	if(append){\n"
	"		fprintf(hader, \"\n\n\n/********************************************%s***********************************************/\n\",matrixName);\n"
	"	}\n"
	"\n"
	"	fprintf(hader, \"static const char %s[]{ \n\t\",matrixName);\n"
	"	\n"
	"	for(u64 i = 0 ; i < sizeofData ; i++){\n"
	"		if(!(i%10)){\n"
	"			fprintf(hader, \"\n\t\");\n"
	"		}\n"
	"		fprintf(hader, \"%d , \",(u32)data[i]);\n"
	"		\n"
	"	}\n"
	"	//fwrite(const void *__restrict ptr, size_t size, size_t n, FILE *__restrict s)\n"
	"	fprintf(hader, \"};\");\n"
	"	fclose(hader);\n"
	"	return;\n"
	"}\n"
	"\n"
	"\n"
	"\n"
	"\n"
	"void* Text2String(char* data, u64* dataSize, u64* usedData){\n"
	"	for(u64 i = *dataSize ; i > 0 ; i--){\n"
	"		if(data[i-1] == '\n'){\n"
	"			data = (char*)Push(\"\t\"\", 2, i, dataSize, usedData, data);\n"
	"			data = (char*)Push(\"\\n\"\", 3, i-1, dataSize, usedData, data);\n"
	"\n"
	"		}\n"
	"		if(data[i-1]=='\"' ){\n"
	"			if(i>2 && data[i-2]=='\\' && data[i-3]!='\\'){\n"
	"				continue;\n"
	"			}\n"
	"			data = (char*)Push(\"\\\", 1, i-1, dataSize, usedData, data);\n"
	"		}\n"
	"	}\n"
	"	if(data[*usedData-1]=='\"'){\n"
	"		data[*usedData-1]='\0';\n"
	"	}\n"
	"\n"
	"	data=(char*)Push(\"\t\"\", 2, 0, dataSize, usedData, data);\n"
	"	return  data;\n"
	"}\n"
	"\n"
	"\n"
	"\n"
	"\n"
	"int main(int argc, char** arg){\n"
	"	printf(\"*** File2.H ***\n\");\n"
	"	if(argc>=2) \n"
	"	{	\n"
	"		u32 arglng = strlen(arg[1]);\n"
	"		if( (arglng==2 & !memcmp(arg[1], \"-h\", 2)) || \n"
	"		    (arglng==6 & !memcmp(arg[1], \"--help\", 6))\n"
	"		  ){\n"
	"			printf(\"Welcome to File2.H!\nthis programe is under the MIT License\ncheckout the github repo: https://github.com/chamseddine2009-06/File2.H\n\n\");\n"
	"			printf(\"===> [arg1 fileName] [arg2 2haderName] [arg3 StringName] -Option1 -Option2 ...\n\"\n"
	"			       \"\nOptions:\n\"	\n"
	"			       \"\t-m or --matrix if you want to save it as matrix not as a string.\n\"\n"
	"			       \"\t-a or --appand if you dont want to over-write the data in the Haderfile.\n\");\n"
	"			return 0;\n"
	"		}\n"
	"	}\n"
	"\n"
	"	if(argc<=3){\n"
	"		printf(\"wrong argmentes struct, type -h for help\n\");\n"
	"		return 1;\n"
	"	}\n"
	"	bool matrixmode = false;\n"
	"	bool appendmode = false;\n"
	"	if(argc>3){\n"
	"		for(int i = 3 ; i < argc ; i++){\n"
	"			if(strlen(arg[i])==2 && !memcmp(arg[i] ,\"-m\", 2)){\n"
	"				printf(\"\nYou are in matrix mode, all the data in your file will save a matrix not a string.\n\");\n"
	"				matrixmode = true;\n"
	"			}\n"
	"			if(strlen(arg[i])==2 && !memcmp(arg[i] ,\"-a\", 2)){\n"
	"				printf(\"\nYou are in appand mode.\n\");\n"
	"				appendmode = true;\n"
	"			}\n"
	"			if(strlen(arg[i])==8 && !memcmp(arg[i] ,\"--matrix\", 8)){\n"
	"				printf(\"\nYou are in matrix mod, all the data in your file will save a matrix not a string.\n\");\n"
	"				matrixmode = true;\n"
	"			}\n"
	"			if(strlen(arg[i])==8 && !memcmp(arg[i] ,\"--append\", 8)){\n"
	"				printf(\"\nYou are in appand mode.\n\");\n"
	"				appendmode = true;\n"
	"			}\n"
	"		}\n"
	"	}\n"
	"		\n"
	"	u64 dataSize=0;\n"
	"	char* data = (char*)readFile(arg[1], &dataSize);\n"
	"	u64 usedData = dataSize;\n"
	"	printf(\"file %s size %d \n\",arg[1],dataSize);\n"
	"	if(!matrixmode){\n"
	"		printf(\"Data size %d\n\" , dataSize);\n"
	"		data = Text2String(data, &dataSize, &usedData);\n"
	"		WriteConstCharHaderFile(arg[2],arg[3], data, usedData,appendmode);\n"
	"	}else {\n"
	"		WriteMatrixHaderFile(arg[2], arg[3], data, dataSize,appendmode);\n"
	"	}\n"
	"	\n"
	"	return 0;\n"
	"\n"
	"}\n"
	;